baseURL = 'https://www.tamaron.dev/hugo-page/'
languageCode = 'en-us'
theme = 'ananke'

Copyright = "tamaron"

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 9

[languages]
[languages.ja]
title = "tamaron"
weight = 1
contentDir = "content/en"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
custom_css = ["custom-font.css"]
recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/tamaroning"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/tamaroning"
